package com.airplayer;

import java.util.HashSet;

public class FormatFilter{
	private HashSet<String> formats;
	
	//File formats:
	//	D. = Demuxing supported
	//	.E = Muxing supported
	public FormatFilter(){
		formats = new HashSet<String>();
		formats.add("3g2"); //3GP2 format
		formats.add("3gp"); //3GP format
		formats.add("4xm"); //4X Technologies format
		formats.add("a64"); //a64 video for Commodore 64
		formats.add("aac"); //raw ADTS AAC
		formats.add("ac3"); //raw AC-3
		formats.add("act"); //ACT Voice file format
		formats.add("adf"); //Artworx Data Format
		formats.add("adts"); //ADTS AAC
		formats.add("adx"); //CRI ADX
		formats.add("aea"); //MD STUDIO audio
		formats.add("aiff"); //Audio IFF
		formats.add("alaw"); //PCM A-law format
		formats.add("amr"); //3GPP AMR file format
		formats.add("anm"); //Deluxe Paint Animation
		formats.add("apc"); //CRYO APC format
		formats.add("ape"); //Monkey's Audio
		formats.add("asf"); //ASF format
		formats.add("asf_stream"); //ASF format
		formats.add("ass"); //Advanced SubStation Alpha subtitle format
		formats.add("au"); //SUN AU format
		formats.add("avi"); //AVI format
		formats.add("avm2"); //Flash 9 (AVM2) format
		formats.add("avs"); //AVISynth
		formats.add("bethsoftvid"); //Bethesda Softworks VID format
		formats.add("bfi"); //Brute Force & Ignorance
		formats.add("bin"); //Binary text
		formats.add("bink"); //Bink
		formats.add("bit"); //G.729 BIT file format
		formats.add("bmv"); //Discworld II BMV
		formats.add("c93"); //Interplay C93
		formats.add("caf"); //Apple Core Audio Format
		formats.add("cavsvideo"); //raw Chinese AVS video
		formats.add("cdg"); //CD Graphics Format
		formats.add("cdxl"); //Commodore CDXL video format
		formats.add("crc"); //CRC testing format
		formats.add("daud"); //D-Cinema audio format
		formats.add("dfa"); //Chronomaster DFA
		formats.add("dirac"); //raw Dirac
		formats.add("dnxhd"); //raw DNxHD (SMPTE VC-3)
		formats.add("dshow"); //DirectShow capture
		formats.add("dsicin"); //Delphine Software International CIN format
		formats.add("dts"); //raw DTS
		formats.add("dv"); //DV video format
		formats.add("dvd"); //MPEG-2 PS format (DVD VOB)
		formats.add("dxa"); //DXA
		formats.add("ea"); //Electronic Arts Multimedia Format
		formats.add("ea_cdata"); //Electronic Arts cdata
		formats.add("eac3"); //raw E-AC-3
		formats.add("f32be"); //PCM 32 bit floating-point big-endian format
		formats.add("f32le"); //PCM 32 bit floating-point little-endian format
		formats.add("f64be"); //PCM 64 bit floating-point big-endian format
		formats.add("f64le"); //PCM 64 bit floating-point little-endian format
		formats.add("ffm"); //FFM (FFserver live feed) format
		formats.add("ffmetadata"); //FFmpeg metadata in text format
		formats.add("film_cpk"); //Sega FILM/CPK format
		formats.add("filmstrip"); //Adobe Filmstrip
		formats.add("flac"); //raw FLAC
		formats.add("flic"); //FLI/FLC/FLX animation format
		formats.add("flv"); //FLV format
		formats.add("framecrc"); //framecrc testing format
		formats.add("framemd5"); //Per-frame MD5 testing format
		formats.add("g722"); //raw G.722
		formats.add("g723_1"); //raw G.723.1
		formats.add("g729"); //G.729 raw format demuxer
		formats.add("gif"); //GIF Animation
		formats.add("gsm"); //raw GSM
		formats.add("gxf"); //GXF format
		formats.add("h261"); //raw H.261
		formats.add("h263"); //raw H.263
		formats.add("h264"); //raw H.264 video format
		formats.add("hls"); //Apple HTTP Live Streaming format
		formats.add("applehttp"); //Apple HTTP Live Streaming format
		formats.add("ico"); //Microsoft Windows ICO
		formats.add("idcin"); //id Cinematic format
		formats.add("idf"); //iCE Draw File
		formats.add("iff"); //Interchange File Format
		formats.add("ilbc"); //iLBC storage file format
		formats.add("image2"); //image2 sequence
		formats.add("image2pipe"); //piped image2 sequence
		formats.add("ingenient"); //raw Ingenient MJPEG
		formats.add("ipmovie"); //Interplay MVE format
		formats.add("ipod"); //iPod H.264 MP4 format
		formats.add("ismv"); //ISMV/ISMA (Smooth Streaming) format
		formats.add("iss"); //Funcom ISS format
		formats.add("iv8"); //A format generated by IndigoVision 8000 video server
		formats.add("ivf"); //On2 IVF
		formats.add("jacosub"); //JACOsub subtitle format
		formats.add("jv"); //Bitmap Brothers JV
		formats.add("latm"); //LOAS/LATM
		formats.add("lavfi"); //Libavfilter virtual input device
		formats.add("libnut"); //nut format
		formats.add("lmlm4"); //lmlm4 raw format
		formats.add("loas"); //LOAS AudioSyncStream
		formats.add("lxf"); //VR native stream format (LXF)
		formats.add("m4v"); //raw MPEG-4 video format
		formats.add("matroska"); //Matroska file format
		formats.add("webm"); //WebM file format
		formats.add("md5"); //MD5 testing format
		formats.add("mgsts"); //Metal Gear Solid: The Twin Snakes
		formats.add("microdvd"); //MicroDVD subtitle format
		formats.add("mjpeg"); //raw MJPEG video
		formats.add("mkvtimestamp_v2"); //extract pts as timecode v2 format, as defined by mkvtoolnix
		formats.add("mlp"); //raw MLP
		formats.add("mm"); //American Laser Games MM format
		formats.add("mmf"); //Yamaha SMAF
		formats.add("mov"); //MOV format
		formats.add("m4a"); //QuickTime/MPEG-4/Motion JPEG 2000 format
		formats.add("mj2"); //QuickTime/MPEG-4/Motion JPEG 2000 format
		formats.add("mp2"); //MPEG audio layer 2
		formats.add("mp3"); //MPEG audio layer 3
		formats.add("mp4"); //MP4 format
		formats.add("mpc"); //Musepack
		formats.add("mpc8"); //Musepack SV8
		formats.add("mpeg"); //MPEG-1 System format
		formats.add("mpeg1video"); //raw MPEG-1 video
		formats.add("mpeg2video"); //raw MPEG-2 video
		formats.add("mpegts"); //MPEG-2 transport stream format
		formats.add("mpegtsraw"); //MPEG-2 raw transport stream format
		formats.add("mpegvideo"); //raw MPEG video
		formats.add("mpjpeg"); //MIME multipart JPEG format
		formats.add("msnwctcp"); //MSN TCP Webcam stream
		formats.add("mtv"); //MTV format
		formats.add("mulaw"); //PCM mu-law format
		formats.add("mvi"); //Motion Pixels MVI format
		formats.add("mxf"); //Material eXchange Format
		formats.add("mxf_d10"); //Material eXchange Format, D-10 Mapping
		formats.add("mxg"); //MxPEG clip file format
		formats.add("nc"); //NC camera feed format
		formats.add("nsv"); //Nullsoft Streaming Video
		formats.add("null"); //raw null video format
		formats.add("nut"); //NUT format
		formats.add("nuv"); //NuppelVideo format
		formats.add("ogg"); //Ogg
		formats.add("oma"); //Sony OpenMG audio
		formats.add("pmp"); //Playstation Portable PMP format
		formats.add("psp"); //PSP MP4 format
		formats.add("psxstr"); //Sony Playstation STR format
		formats.add("pva"); //TechnoTrend PVA file and stream format
		formats.add("qcp"); //QCP format
		formats.add("r3d"); //REDCODE R3D format
		formats.add("rawvideo"); //raw video format
		formats.add("rcv"); //VC-1 test bitstream
		formats.add("realtext"); //RealText subtitle format
		formats.add("rl2"); //RL2 format
		formats.add("rm"); //RealMedia format
		formats.add("roq"); //raw id RoQ format
		formats.add("rpl"); //RPL/ARMovie format
		formats.add("rso"); //Lego Mindstorms RSO format
		formats.add("rtp"); //RTP output format
		formats.add("rtsp"); //RTSP output format
		formats.add("s16be"); //PCM signed 16 bit big-endian format
		formats.add("s16le"); //PCM signed 16 bit little-endian format
		formats.add("s24be"); //PCM signed 24 bit big-endian format
		formats.add("s24le"); //PCM signed 24 bit little-endian format
		formats.add("s32be"); //PCM signed 32 bit big-endian format
		formats.add("s32le"); //PCM signed 32 bit little-endian format
		formats.add("s8"); //PCM signed 8 bit format
		formats.add("sami"); //SAMI subtitle format
		formats.add("sap"); //SAP output format
		formats.add("sbg"); //SBaGen binaural beats script
		formats.add("sdl"); //SDL output device
		formats.add("sdp"); //SDP
		formats.add("segment"); //segment muxer
		formats.add("shn"); //raw Shorten
		formats.add("siff"); //Beam Software SIFF
		formats.add("smjpeg"); //Loki SDL MJPEG
		formats.add("smk"); //Smacker video
		formats.add("smush"); //LucasArts Smush
		formats.add("sol"); //Sierra SOL format
		formats.add("sox"); //SoX native format
		formats.add("spdif"); //IEC 61937 (used on S/PDIF - IEC958)
		formats.add("srt"); //SubRip subtitle format
		formats.add("stream_segment"); //streaming segment muxer
		formats.add("ssegment"); //streaming segment muxer
		formats.add("svcd"); //MPEG-2 PS format (VOB)
		formats.add("swf"); //Flash format
		formats.add("thp"); //THP
		formats.add("tiertexseq"); //Tiertex Limited SEQ format
		formats.add("tmv"); //8088flex TMV
		formats.add("truehd"); //raw TrueHD
		formats.add("tta"); //True Audio
		formats.add("tty"); //Tele-typewriter
		formats.add("txd"); //Renderware TeXture Dictionary
		formats.add("u16be"); //PCM unsigned 16 bit big-endian format
		formats.add("u16le"); //PCM unsigned 16 bit little-endian format
		formats.add("u24be"); //PCM unsigned 24 bit big-endian format
		formats.add("u24le"); //PCM unsigned 24 bit little-endian format
		formats.add("u32be"); //PCM unsigned 32 bit big-endian format
		formats.add("u32le"); //PCM unsigned 32 bit little-endian format
		formats.add("u8"); //PCM unsigned 8 bit format
		formats.add("vc1"); //raw VC-1
		formats.add("vc1test"); //VC-1 test bitstream format
		formats.add("vcd"); //MPEG-1 System format (VCD)
		formats.add("vfwcap"); //VfW video capture
		formats.add("vmd"); //Sierra VMD format
		formats.add("vob"); //MPEG-2 PS format (VOB)
		formats.add("voc"); //Creative Voice file format
		formats.add("vqf"); //Nippon Telegraph and Telephone Corporation (NTT) TwinVQ
		formats.add("w64"); //Sony Wave64 format
		formats.add("wav"); //WAV format
		formats.add("wc3movie"); //Wing Commander III movie format
		formats.add("webm"); //WebM file format
		formats.add("wsaud"); //Westwood Studios audio format
		formats.add("wsvqa"); //Westwood Studios VQA format
		formats.add("wtv"); //Windows Television (WTV)
		formats.add("wv"); //WavPack
		formats.add("xa"); //Maxis XA File Format
		formats.add("xbin"); //eXtended BINary text (XBIN)
		formats.add("xmv"); //Microsoft XMV
		formats.add("xwma"); //Microsoft xWMA
		formats.add("yop"); //Psygnosis YOP Format
		formats.add("yuv4mpegpipe"); //YUV4MPEG pipe format	
		formats.add("mkv"); //	
		formats.add("ts"); //	
	}
	
	public boolean isSupportFormat(String filename){
		//get the position of the last '.'
		int index = filename.lastIndexOf('.');
		
		//return false if there is no suffix format
		if(index == -1 || index == filename.length())
			return false;
		
		//get the suffix of the filename
		String suffix = filename.substring(index + 1).trim();
		
		//check whether the format is supported by ffmpeg.
		return formats.contains(suffix);
	}
	
	
	public static void main(String[] args){
		FormatFilter filter = new FormatFilter();
		System.out.println(filter.isSupportFormat("gfgdf.3gp"));
		System.out.println(filter.isSupportFormat("hfghfg.xvg"));
		System.out.println(filter.isSupportFormat("hfghfg.yop"));
		System.out.println(filter.isSupportFormat("mkv.xvg"));
		System.out.println(filter.isSupportFormat(".mkv."));
	}
}
